name: 'Scan TLDs'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '27 * * * *' # every hour at minute 27

jobs:
  scan:
    # ensure this push wasn't a zonefile update, to prevent a commit loop
    if: "!contains(github.event.head_commit.message, 'Zonefile updates')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        persist-credentials: true
    - uses: actions/setup-python@v4
      with:
        python-version: '2.7.18'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - run: ./scan.sh
    - name: Commit files
      run: |
        git config --local user.email "tldr-updates@chary.us"
        git config --local user.name "TLDR Update GitHub Action"
        git add .
        git commit -m "Zonefile updates ($(date -u +"%x %H:%M"))" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        ssh: true
        branch: ${{ github.ref }}
